// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlm4ZC-s6ADb3GeBHblVOXSNbZtYPYICU',
    appId: '1:477861815796:web:664e6d0116991e1a3f05a1',
    messagingSenderId: '477861815796',
    projectId: 'fir-keyfa',
    authDomain: 'fir-keyfa.firebaseapp.com',
    storageBucket: 'fir-keyfa.firebasestorage.app',
    measurementId: 'G-BB7XDNS92T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIeolRRPiMMGGoT_nZNBoSXauv4m_bCos',
    appId: '1:477861815796:android:46b4d9ebcb2de3423f05a1',
    messagingSenderId: '477861815796',
    projectId: 'fir-keyfa',
    storageBucket: 'fir-keyfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2AHeTsCdho2O6wWw_g5AIr-U1E2Xcecc',
    appId: '1:477861815796:ios:1e5314261805f5183f05a1',
    messagingSenderId: '477861815796',
    projectId: 'fir-keyfa',
    storageBucket: 'fir-keyfa.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2AHeTsCdho2O6wWw_g5AIr-U1E2Xcecc',
    appId: '1:477861815796:ios:1e5314261805f5183f05a1',
    messagingSenderId: '477861815796',
    projectId: 'fir-keyfa',
    storageBucket: 'fir-keyfa.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlm4ZC-s6ADb3GeBHblVOXSNbZtYPYICU',
    appId: '1:477861815796:web:58604782ad75c6ef3f05a1',
    messagingSenderId: '477861815796',
    projectId: 'fir-keyfa',
    authDomain: 'fir-keyfa.firebaseapp.com',
    storageBucket: 'fir-keyfa.firebasestorage.app',
    measurementId: 'G-WMPHKC4L6Y',
  );

}